# Generated by Django 5.2.1 on 2025-06-22 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_ingredientinrecipe_recipe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'default_related_name': 'in_shopping_cart', 'verbose_name': 'список покупок', 'verbose_name_plural': 'списки покупок'},
        ),
    ]
