# Generated by Django 5.2.1 on 2025-06-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_ingredients_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='recipes_images/', verbose_name='изображение рецепта'),
        ),
    ]
