# Generated by Django 5.2.1 on 2025-06-22 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_shoppingcart_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'default_related_name': 'favorite', 'verbose_name': 'избранный рецепт', 'verbose_name_plural': 'избранные рецепты'},
        ),
    ]
