# Generated by Django 5.2.1 on 2025-06-28 02:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_favorite_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagsofrecipe',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='tagsofrecipe',
            name='tag',
        ),
        migrations.RemoveConstraint(
            model_name='favorite',
            name='unique_favorite',
        ),
        migrations.RemoveConstraint(
            model_name='shoppingcart',
            name='shopping_cart',
        ),
        migrations.AlterField(
            model_name='recipes',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='время приготовления'),
        ),
    ]
