# Константы для приложения Users:
MAX_LENGTH_USERNAME = 150
MAX_LENGTH_EMAIL = 254
MAX_LENGTH_FIRSTNAME = 150
MAX_LENGTH_SECONDNAME = 150
# Константы для приложения Recipes:
MAX_LENGTH_RECIPE_NAME = 256
MAX_LENGTH_INGREDIENT_NAME = 128
MAX_LENGTH_MEASUREMENT_UNIT = 64
MAX_LENGTH_TAG_NAME = 32
MAX_LENGTH_TAG_SLUG = 32
MIN_VALUE_COOKING_TIME = 1
# Константы для приложения API:
PAGE_SIZE = 6
