# Generated by Django 5.2.1 on 2025-06-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_myuser_options_alter_subscribes_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'ordering': ['username'], 'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='электронная почты'),
        ),
        migrations.AddConstraint(
            model_name='subscribes',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='unique_subscribes'),
        ),
    ]
